### ISSUE TITLE
TrustedHTML issues in Chrome/Brave

### ISSUE THREAD

**Issue by hydrian** [mrjones-plip/timekpr-next-remote#11]
Receiving multiple 'This document requires 'TrustedHTML' assignment.' errors in the for javascript in the web devel console. It is not rendering the page correctly. This looks like a CSP policy issue.

**Comment by hydrian** [comment]
Verified that there is CSP TrustedHTML issue. Installed "Disable Content Security Policy" extension to verify CSP issue. After the extension was activated, the webapp was working correctly.

**Comment by hydrian** [comment]
Testing through a reverse proxy.

**Comment by mrjones-plip** [comment]
Hey @hydrian - thanks for reporting the issue!  

I'm having trouble understand this.  Can you please provide a numbered steps to reproduce this?  Please be sure to provide:

1. screen shot showing  page not rendering correctly and the web devel console open with the error
2. browser and version you're using (you mention "Chrome/Brave", but please specify which it is, or both, and versions)
3. client OS/version
4. hosting setup (docker version? reverse proxy name and version?)

Oh yes!  Are you able to test if the error happens when you directly hit the server, bypassing the reverse proxy?  I understand this may not be possible depending on your network/server setup.

thanks!

**Comment by hydrian** [comment]
Browser fails in both desktop and mobile version of both Brave and Chrome.

* Brave 1.64.116, Chromium 123.0.6312.105
* Chrome 123.0.6312.99

Nginx 1.18.0 (Ubuntu 20.04)

I deployed it with docker in bridge mode. The reverse proxy is on the same host. I'm mainly using it for authentication.

**Comment by hydrian** [comment]
Browser fails in both desktop and mobile version of both Brave and Chrome.

* Brave 1.64.116, Chromium 123.0.6312.105
* Chrome 123.0.6312.99

Nginx 1.18.0 (Ubuntu 20.04)

I deployed it with docker in bridge mode. The reverse proxy is on the same host. I'm mainly using it for authentication.

**Comment by hydrian** [comment]
Nevermind. Nut behind the keyboard. My proxy was injecting CSP. Removed the overrides and it is working properly now.

**Comment by mrjones-plip** [comment]
@hydrian - Yay!  I'm glad you figured it out.  Thanks for updating the ticket with the solution and closing it out.
